// Windows 98 스타일 도트 아이콘. 직접 그린 그림이며 마이크로소프트의 아이콘 파일이 아닙니다.
// 표준 16색 팔레트만 씁니다. 글자 하나가 픽셀 하나이고 '.'은 투명입니다.
// 기본은 16x16이고, 이름 뒤에 @32가 붙은 것은 32px 이상으로 보여 줄 때 쓰는 32x32 정밀판입니다.
// (Windows 98도 아이콘마다 16px판과 32px판을 따로 그렸습니다.)

export const PALETTE = {
  k: '#000000',
  d: '#808080',
  s: '#c0c0c0',
  w: '#ffffff',
  r: '#ff0000',
  R: '#800000',
  y: '#ffff00',
  o: '#808000',
  g: '#00ff00',
  G: '#008000',
  c: '#00ffff',
  t: '#008080',
  b: '#0000ff',
  n: '#000080',
  m: '#ff00ff',
  p: '#800080',
}

export const ICONS = {
  library: [
    '................',
    '................',
    '.....kkkkkk.....',
    '.....krrrRk.....',
    'kkkkkkrrrRk.....',
    'kbbbnkyyyRkkkkkk',
    'kwwwnkrrrRkgGGGk',
    'kbbbnkrrrRkgGGGk',
    'kbbbnkrrrRkgwwwk',
    'kbbbnkrrrRkgGGGk',
    'kbbbnkyyyRkgGGGk',
    'kwwwnkrrrRkgwwwk',
    'kbbbnkrrrRkgGGGk',
    'kkkkkkkkkkkkkkkk',
    'oooooooooooooooo',
    'kkkkkkkkkkkkkkkk',
  ],
  'folder-open': [
    '................',
    '................',
    '................',
    '.kkkkk..........',
    '.kooookkkkkkkk..',
    '.koooooooooook..',
    '.kokkkkkkkkkkkk.',
    '.kokyyyyyyyyyyyk',
    '.kkywwwwwwwwwyyk',
    '.kkyyyyyyyyyyyyk',
    '.kyyyyyyyyyyyyyk',
    '.kyyyyyyyyyyyyyk',
    'kyyyyyyyyyyyyyyk',
    'kyyyyyyyyyyyyykk',
    'kkkkkkkkkkkkkk..',
    '................',
  ],
  floppy: [
    '................',
    '.kkkkkkkkkkkkk..',
    '.knnkssskksknnk.',
    '.knnkssskksknnk.',
    '.knnkssskksknnk.',
    '.knnkkkkkkkknnk.',
    '.knnnnnnnnnnnnk.',
    '.knnnnnnnnnnnnk.',
    '.knkkkkkkkkkknk.',
    '.knkwwwwwwwwknk.',
    '.knkbbbbbbbbknk.',
    '.knkwwwwwwwwknk.',
    '.knkbbbbbbbbknk.',
    '.knkwwwwwwwwknk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  notepad: [
    '....k..k..k.....',
    '....d..d..d.....',
    '..kkdkkdkkdkkk..',
    '..kwkwwkwwkwwd..',
    '..kwwwwwwwwwwd..',
    '..kwwwwwwwwwwd..',
    '..kwbbbbbbbbwd..',
    '..kwwwwwwwwwwd..',
    '..kwbbbbbbbbwd..',
    '..kwwwwwwwwwwd..',
    '..kwbbbbbbbbwd..',
    '..kwwwwwwwwwwd..',
    '..kwbbbbbwwwwd..',
    '..kwwwwwwwwwwd..',
    '..kddddddddddd..',
    '................',
  ],
  trash: [
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.ksddddddddddsk.',
    '..kwdsdsdsdsdk..',
    '..kwssssssssdk..',
    '..kwdsdGgsdsdk..',
    '..kwssGssGssdk..',
    '..kwdsGwdgdsdk..',
    '...kwGssssGdk...',
    '...kwGgGGGGdk...',
    '...kwssssssdk...',
    '...kwsdsdsddk...',
    '....kkkkkkkk....',
  ],
  'trash-full': [
    '...kkkkk........',
    '...kwwwkkkkwk...',
    '...kdwwkwwwwk...',
    '...kdddkddddk...',
    '..kkkkkkkkkkkk..',
    '.ksddddddddddsk.',
    '..kwdsdsdsdsdk..',
    '..kwssssssssdk..',
    '..kwdsdGgsdsdk..',
    '..kwssGssGssdk..',
    '..kwdsGwdgdsdk..',
    '...kwGssssGdk...',
    '...kwGgGGGGdk...',
    '...kwssssssdk...',
    '...kwsdsdsddk...',
    '....kkkkkkkk....',
  ],
  'trash@32': [
    '................................',
    '................................',
    '...........wsss.................',
    '.........wwkkkdssss.............',
    '......dwwkkdddkkkkdssss.........',
    '....dwwkkdddddddddkkkkdssss.....',
    '...wwwkdddddddddddddddkkkkdsss..',
    '...wwwwwwwddddddddddddddddddkk..',
    '...dsswwwwwwwwdddddddddddddddk..',
    '....wwsssswwwwwwwwddddddddddk...',
    '....wwsssssssswwwwwwwdsdddddk...',
    '....wwsssssssssssswwwsddddddk...',
    '....dwwsssssssssssssddsdddddk...',
    '....dwwsssssGGGsssssdsddddddk...',
    '....dwwsgggsGGGGssssddsdddd.k...',
    '.....wwGGgggsGGGGsssdsdddddk....',
    '.....dwGGsgssssGGsssddsddddk....',
    '.....dGGGssssssGGGssdsdddddk....',
    '.....dGGssssssssGsggddsddddk....',
    '.....dGGsssssssggggsdsdddddk....',
    '......GGGsssssssggsdddsdddk.....',
    '......dwwssssssGsssddsddddk.....',
    '......dwwggssGGGGssdsdsdddk.....',
    '......dwwggGGGGGsssddsddddk.....',
    '......dswggGGGGssssdsdsdddk.....',
    '......dswwsssssssssddsddd.k.....',
    '.......dwwsssssssssdsdsddk......',
    '.......ddssssssssssddsddkk......',
    '.......kkddddssssssdsdkkkk......',
    '.........kkkkddddssdkkkk........',
    '.............kkkkddkkk..........',
    '.................kkd............',
  ],
  'trash-full@32': [
    '............d...................',
    '...........wdd....wd............',
    '...........dsd...wdsd...........',
    '..........sdswd.wdswd...wd......',
    '......d...dwwsdwdsswwd.wdd......',
    '......dd..dwwswdwwswwdwdswd.....',
    '......dsddwswswswwswwwdwswd.....',
    '.....wdswdwwwswswsswwwswswwd....',
    '.....dwwswwwwsswwswwwswwswwd....',
    '.....dwwswwwwwswwswwwswswwwwd...',
    '....wwwwwswwwwswwwwwswwswwwdd...',
    '....wwwwwwwwwwswwwwwswwwddddk...',
    '....dsswwwwwwwwwwwwwwdddddddk...',
    '.....wwssssswwwwwwwwwdddddd.k...',
    '.....wwssssssssssswwwdsddddk....',
    '.....dwwsgsssGGGssssdsdddddk....',
    '.....dwwsGgggGGGGsssddsddddk....',
    '......wwGGGggssGGGssdsdddddk....',
    '......dwGGssssssGGssddsddddk....',
    '......dwGGssssssGssgdsdddd.k....',
    '......dwGGssssssgggsddsdddk.....',
    '......dwGGssssssggssdsddddk.....',
    '.......dwwssgssGsssdsdsdddk.....',
    '.......dwwggGGGGGssddsddddk.....',
    '.......dwwggGGGGsssdsdsdddk.....',
    '.......dswwgsssssssddsddd.k.....',
    '........dwwssssssssdsdsddk......',
    '........dddssssssssddsddkk......',
    '........kkkddddddssdskkkkk......',
    '...........kkkkkkddkkkkk........',
    '.................kkdk...........',
    '................................',
  ],
  trophy: [
    '................',
    '....kkkkkkkk....',
    '.kkkkwyyyyokkkk.',
    '.k..kwyyyyok..k.',
    '.k..kwyyyyok..k.',
    '.k..kwyyyyok..k.',
    '..kkkyyyyyokkk..',
    '.....kkkkkk.....',
    '......kkkk......',
    '......kook......',
    '......kook......',
    '...kkkkkkkkkk...',
    '...kyyyyyyyyk...',
    '...kooooooook...',
    '...kkkkkkkkkk...',
    '................',
  ],
  chart: [
    '................',
    'kkkkkkkkkkkkkkkk',
    'knnnnnnnnnnnnnnk',
    'knnnnnnnnnnnnnnk',
    'kwwwwwwwwwwwwwwk',
    'kwkwwwwwwwGGwwwk',
    'kwkwwwwwwwGGwwwk',
    'kwkwwwwbbwGGwwwk',
    'kwkwwwwbbwGGwywk',
    'kwkwrrwbbwGGwywk',
    'kwkwrrwbbwGGwywk',
    'kwkwrrwbbwGGwywk',
    'kwkkkkkkkkkkkkwk',
    'kwwwwwwwwwwwwwwk',
    'kkkkkkkkkkkkkkkk',
    '................',
  ],
  quote: [
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kwyyyyyyyyyyyk.',
    '.kwnnynnyydddyk.',
    '.kwnnynnyyyyyyk.',
    '.kwnyynyyydddyk.',
    '.kwyyyyyyyyyyyk.',
    '.kwddddddddddyk.',
    '.kwyyyyyyyyyyyk.',
    '.kkkkyyykkkkkkk.',
    '....kyyk........',
    '....kyk.........',
    '....kk..........',
    '................',
    '................',
  ],
  computer: [
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kwwwwwwwwwwwwk.',
    '.kwkkkkkkkkkkdk.',
    '.kwkwwwtttttkdk.',
    '.kwkwtttttttkdk.',
    '.kwkttttttttkdk.',
    '.kwkttttttttkdk.',
    '.kwkttttttttkdk.',
    '.kwkkkkkkkkkkdk.',
    '.kwsssssssssgdk.',
    '.kkdddksskddddk.',
    '......kssk......',
    '...kssssssssk...',
    '...kddddddddk...',
    '................',
  ],
  'book-open': [
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    'kwwwwwwkwwwwwwwk',
    'kwddddwkwdddddwk',
    'kwwwwwwkwwwwwwwk',
    'kwddddwkwdddddwk',
    'kwwwwwwkwwwwwwwk',
    'kwddddwkwdddddwk',
    'kwwwwwwkwwwwwwwk',
    'kwddddwkwdddddwk',
    'kkkkkkkkkkkkkkkk',
    'nbbbbbbbbbbbbbbn',
    'nnnnnnnnnnnnnnnn',
    '................',
  ],
  warning: [
    '................',
    '.......kk.......',
    '.......kk.......',
    '......kyyk......',
    '......kyyk......',
    '.....kykkyk.....',
    '.....kykkyk.....',
    '....kyykkyyk....',
    '....kyykkyyk....',
    '...kyyykkyyyk...',
    '...kyyyyyyyyk...',
    '..kyyyykkyyyyk..',
    '..kyyyykkyyyyk..',
    '.kyyyyyyyyyyyyk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  'document-new': [
    '...r............',
    '...ykkkkkkkk....',
    '..yyywwwwwwsk...',
    'ryywyyrwwwwkk...',
    '..yyywwwwwwwk...',
    '...ywwwwwwwwk...',
    '...rwwwwwwwwk...',
    '...kwddddddwk...',
    '...kwwwwwwwwk...',
    '...kwddddddwk...',
    '...kwwwwwwwwk...',
    '...kwddddddwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kkkkkkkkkk...',
    '................',
  ],
}
